name: CI

on: [push]

env:
  stuff: "wow"
  starts: ${{ startsWith(github.ref, 'refs/tags/asd') }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.13'
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules
    - name: Set up deps
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Compile
      run: npm run compile
    - name: Run app ${{ env.stuff }}
      run: node ./dist/index.js

  job1:
    runs-on: ubuntu-latest
    steps: 
    - name: Set output
      id: set-output
      run: |
        echo "$starts"
        echo "::set-output name=TEST_OUTPUT::testing"
    outputs:
      TEST_OUTPUT: ${{ steps.set-output.outputs.TEST_OUTPUT }}
      
  job2:
    name: Job ${{ env.stuff }} ${{ needs.job1.outputs.TEST_OUTPUT }}
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: Am I ${{ needs.job1.outputs.TEST_OUTPUT }}
        run: echo "Woot"
