name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up deps
      run: |
        nvm use
        npm install
    - name: Lint
      run: npm run lint
    - name: Compile
      run: npm run compile
    - name: Run app
      run: node ./dist/index.js
