name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.13'

    - name: Set up deps
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Compile
      run: npm run compile
    - name: Run app
      run: node ./dist/index.js
